//
//  AudioManifest.generated.swift
//  Generated by scripts/generate-audio-manifest.mjs. Do not edit.
//

enum GeneratedAudioManifest {
    struct Track: Sendable {
        let id: String
        let sha256: String
        let bytes: Int64
    }

    static let catalogVersion = "v1"
    static let fileExtension = "m4a"
    static let cdnPathPrefix = "audio"
    static let appleAssetPackIDPrefix = "org.fuxuan.lengyan.audio."
    static let appleRelativeDirectory = "Audio"
    static let nowPlayingArtist = "屏東能淨協會讀誦"

    static let tracks: [Track] = [
        Track(
            id: "ly01",
            sha256: "981ed4e96be6bf23694d3ad4dda4958fc987295fa895d229df1138f87674ae5a",
            bytes: 11_408_933
        ),
        Track(
            id: "ly02",
            sha256: "86e26f96f26f51c7d94bb9763ae8da5cdc2d7c29f4e3f963ffbc19629725f472",
            bytes: 14_772_155
        ),
        Track(
            id: "ly03",
            sha256: "b2170f364da0d44dd7b1242c73b784eb0f8243e19946591cbdeee90a7b670d55",
            bytes: 15_582_450
        ),
        Track(
            id: "ly04",
            sha256: "34dbd536f603b32ac4fc0316201cd65fe8fbbee504196470fce2b4ac4fa7c840",
            bytes: 16_602_673
        ),
        Track(
            id: "ly05",
            sha256: "f8669fe34c8bd95093679c7d25e16dfdb72cc8d15601987dbaf49bb3dde6151c",
            bytes: 13_012_100
        ),
        Track(
            id: "ly06",
            sha256: "53ce455f3a20cc09e49f05ae2632fafd8c1c686529d5bf9ecdd32f3465a39828",
            bytes: 14_330_690
        ),
        Track(
            id: "ly07",
            sha256: "c4b879afc23d06fbcf4af2ed81d5b9680797fa0860a0f9804531da95668813a7",
            bytes: 16_483_037
        ),
        Track(
            id: "ly08",
            sha256: "7a31de382ed9bfc523ec4a49792055249d378a32c8d5cde8b8b3bea928b01e96",
            bytes: 15_602_303
        ),
        Track(
            id: "ly09",
            sha256: "a0f8ad5c1cdde15243d150e510368f43d327fe42f5ef1e362e704971cedde801",
            bytes: 21_116_150
        ),
        Track(
            id: "ly10",
            sha256: "e531560f540e74fd3088201de8e164007dfb71434ec55f43d751c92b11feff2c",
            bytes: 16_590_672
        ),
        Track(
            id: "lyz1",
            sha256: "33734314186b1229a08b85169c6b481ed9401cf94ae636f4b36340f11d1db2e0",
            bytes: 5_919_555
        )
    ]
}
